
type Food = enum {
	Apple Num
	Banana Num
	Cereal Num
	Milk #(String Num)
}

type Utils = enum {
	Paper Num
	Detergent Num
	Pencils Num
}

type Packaging = enum {
	Bag
	PlasticBag
}

type ShoppingList = rec {
	food: Food
	utils: Utils
	packaging: Packaging
}

type NestedHell = enum {
	NoNesting Num
	Nesting enum {
		FirstLevel enum {
			SecondLevel enum {
				Third Lvl<a>
			}
			Second rec {
				first: Num
				second: Num
			}
		}
		StillFirst Num<a>
	}
}
